// Compatibility entry point for the transient navigation worker.
//
// Keep these implementation fragments in one translation unit: the worker's
// hot path relies on internal linkage and whole-file optimization, while the
// responsibility-based files make the implementation navigable.
#include "worker/finder_ax_step/prelude.inc"
#include "worker/finder_ax_step/accessibility_primitives.inc"
#include "worker/finder_ax_step/finder_accessibility.inc"
#include "worker/finder_ax_step/navigation_context.inc"
#include "worker/finder_ax_step/item_resolution.inc"
#include "worker/finder_ax_step/selection_core.inc"
#include "worker/finder_ax_step/selection_state.inc"
#include "worker/finder_ax_step/selection_clear.inc"
#include "worker/finder_ax_step/process_locks.inc"
#include "worker/finder_ax_step/keyboard_events.inc"
#include "worker/finder_ax_step/scroll_events.inc"
#include "worker/finder_ax_step/vertical_movement.inc"
#include "worker/finder_ax_step/grid_movement.inc"
#include "worker/finder_ax_step/movement_dispatch.inc"
#include "worker/finder_ax_step/hold_tokens.inc"
#include "worker/finder_ax_step/runtime_support.inc"
#include "worker/finder_ax_step/metrics.inc"
#include "worker/finder_ax_step/worker_transport.inc"
#include "worker/finder_ax_step/navigation_transition.inc"
#include "worker/finder_ax_step/worker_lifecycle.inc"
#include "worker/finder_ax_step/worker_client.inc"
#include "worker/finder_ax_step/hold_state_tokens.inc"
#include "worker/finder_ax_step/hold_configuration.inc"
#include "worker/finder_ax_step/hold_position.inc"
#include "worker/finder_ax_step/hold_scroll.inc"
#include "worker/finder_ax_step/hold_fast_ax.inc"
#include "worker/finder_ax_step/hold_native_list.inc"
#include "worker/finder_ax_step/hold_controller.inc"
#include "worker/finder_ax_step/edge_monitor_state.inc"
#include "worker/finder_ax_step/edge_monitor_lock.inc"
#include "worker/finder_ax_step/edge_probe.inc"
#include "worker/finder_ax_step/column_stall_state.inc"
#include "worker/finder_ax_step/column_edge_context.inc"
#include "worker/finder_ax_step/column_edge_monitor.inc"
#include "worker/finder_ax_step/list_edge_monitor.inc"
#include "worker/finder_ax_step/edge_monitor_worker.inc"
#include "worker/finder_ax_step/edge_monitor_commands.inc"
#include "worker/finder_ax_step/cli_commands.inc"
#include "worker/finder_ax_step/cli.inc"
